name: Docker Custom Action Greetings
author: Keyhan Saldjoughi
description: "Greet someone and record the time"
inputs:
  who_to_greet:
    description: "Who to greet"
    default: "World"
outputs:
  time:
    description: The time of the greeting
runs:
  using: "docker"
  #image: 'docker://node:18.16-alpine3.17'
  # or locally
  image: "Dockerfile"
  args: #override the CMD[world] and let user put in the world
    - ${{ inputs.who_to_greet }}
  env:
    HELLO: WORLD
